# Generated by Django 4.2.29 on 2026-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealshub', '0003_remove_order_date_order_week_number_alter_meal_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4')], max_length=50),
        ),
    ]
