# Generated by Django 4.2.29 on 2026-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealshub', '0004_alter_order_student_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='class_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
